//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TClient()
        {
            this.TContact = new HashSet<TContact>();
        }
    
        public int IdClient { get; set; }
        public string RaisonSociale { get; set; }
        public string TypeSociete { get; set; }
        public string Activite { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string Nature { get; set; }
        public decimal Ca { get; set; }
        public int Effectif { get; set; }
        public string CommentComm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TContact> TContact { get; set; }
    }
}
