//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContact
    {
        public int IdContact { get; set; }
        public string NomContact { get; set; }
        public string PrenomContact { get; set; }
        public string TelContact { get; set; }
        public string FonctionContact { get; set; }
        public Nullable<decimal> TotalHeuresContact { get; set; }
        public int IdClient { get; set; }
    
        public virtual TClient TClient { get; set; }
    }
}
